### ISSUE TITLE
zzpj Events To-do List

### ISSUE THREAD

**Issue by KapravveOczko** [KapravveOczko/zzpj#1]
### 1. Project Documentation
- [x] Creation of the E\/enTs project vision document.
- [ ] Development of the requirements specification document.

### 2. Backend Implementation
- [x] Creation of user registration and login module.
- [x] Implementation of the mechanism for adding new events.
- [x] Development of the system for users to join existing events.
- [x] Setting up the SQLite database handling.

### 3. User Interface Creation
- [ ] Design of a responsive user interface.
- [ ] Implementation of views for browsing available events.
- [ ] Creation of a form for adding new events.
- [ ] Development of a user panel for managing events.

### 4. Integration with External APIs
- [ ] Integration with Google Maps API for event locations.
- [ ] Implementation of integration with Google Calendar API for calendar management.

### 5. Testing and Documentation
- [x] Execution of unit tests for backend modules.
- [ ] Conducting integration testing of the entire application.
- [ ] Creation of code documentation for clarity of application structure.
- [ ] Preparation of user documentation for easy use of the application.
